apiVersion: v1
kind: Service
metadata:
  name: vanillatstodo
  labels:
    app: vanillatstodo
    environment: experimental
    managed-by: kubectl
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
spec:
  selector:
    app: vanillatstodo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
