apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanillatstodo
  labels:
    app: vanillatstodo
    environment: experimental
    version: "0.0.1"
    managed-by: kubectl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vanillatstodo
  template:
    metadata:
      labels:
        app: vanillatstodo
        version: "0.0.1"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
        - name: vanillatstodo
          image: hftamayo/vanillatstodo:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          # Health checks disabled for static React app
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          env:
            - name: NODE_ENV
              value: "experimental"
      imagePullSecrets:
        - name: regcred
      # Security context disabled for debugging
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
