apiVersion: v1
kind: Service
metadata:
  name: vanillatstodo
spec:
  selector:
    app: vanillatstodo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #if I won't use Ingress API: LoadBalancer