apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanillatstodo
  labels:
    app: vanillatstodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vanillatstodo
  template:
    metadata:
      labels:
        app: vanillatstodo
    spec:
      containers:
      - name: vanillatstodo
        image: hftamayo/vanillatstodo:0.0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
