# Default values for vanillatstodo
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

app:
  name: vanillatstodo
  version: "0.0.1"
  environment: base

image:
  repository: hftamayo/vanillatstodo
  tag: "0.0.1"
  pullPolicy: IfNotPresent

deployment:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations: {}
  externalTrafficPolicy: Cluster

healthChecks:
  enabled: true
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 15
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 30

security:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000

imagePullSecrets:
  - name: regcred

monitoring:
  prometheus:
    scrape: true
    port: "80"
